//! # Friend Relationship Model
//!
//! Represents a relationship between two friends.
//! This tracks how friends know each other (e.g., siblings, coworkers).

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Database model for the `friend_relationships` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `user_id`: Foreign key to the owning user (for data isolation)
/// - `friend_a_id`: First friend in the relationship
/// - `friend_b_id`: Second friend in the relationship
/// - `a_to_b`: How friend A relates to friend B (required)
/// - `b_to_a`: How friend B relates to friend A (optional for symmetric relationships)
/// - `created_at`: When the relationship was created
/// - `updated_at`: When the relationship was last modified
///
/// # Relationship Types
///
/// ## Symmetric Relationships
/// When `b_to_a` is NULL, the relationship is symmetric - both friends have
/// the same relation to each other.
/// - Example: "sibling of" (if A is B's sibling, B is A's sibling)
/// - Example: "friend of" (mutual friendship)
///
/// ## Asymmetric Relationships
/// When `b_to_a` is set, each direction can have a different label.
/// - Example: a_to_b = "boss of", b_to_a = "employee of"
/// - Example: a_to_b = "mentor to", b_to_a = "mentee of"
///
/// # Data Isolation
/// The `user_id` ensures users only see relationships between their own friends.
/// Both `friend_a_id` and `friend_b_id` must belong to the same user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FriendRelationship {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// Foreign key to the owning user - for data isolation
    pub user_id: Uuid,

    /// First friend in the relationship
    pub friend_a_id: Uuid,

    /// Second friend in the relationship
    pub friend_b_id: Uuid,

    /// How friend A relates to friend B (e.g., "sibling of", "boss of")
    pub a_to_b: String,

    /// How friend B relates to friend A (optional)
    /// If NULL, the relationship is symmetric (same in both directions)
    pub b_to_a: Option<String>,

    /// Timestamp when the relationship was created
    pub created_at: OffsetDateTime,

    /// Timestamp when the relationship was last updated
    pub updated_at: Option<OffsetDateTime>,
}
