//! # Friend Model
//!
//! Represents a friend record in the `friends` table.
//! This is the core entity of the Friend Knowledgebase - each friend
//! belongs to a user and can have groups, attributes, and relationships.

use serde::{Deserialize, Serialize};
use time::{Date, OffsetDateTime};
use uuid::Uuid;

/// Database model for the `friends` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `user_id`: Foreign key to the owning user (for data isolation)
/// - `first_name`: Friend's first name (required)
/// - `last_name`: Friend's last name (optional)
/// - `date_of_birth`: Friend's birthday for reminders (optional)
/// - `likes`: Things the friend likes (freeform text)
/// - `dislikes`: Things the friend dislikes (freeform text)
/// - `notes`: General notes about the friend
/// - `created_at`: When the record was created
/// - `updated_at`: When the record was last modified
///
/// # Data Isolation
/// Friends are always filtered by `user_id` to ensure users only see
/// their own friends. The `user_id` field links to the `users` table
/// with cascading delete - if a user is deleted, all their friends are too.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Friend {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// Foreign key to the owning user - all queries filter by this
    pub user_id: Uuid,

    /// Friend's first name (required field)
    pub first_name: String,

    /// Friend's last name (optional)
    pub last_name: Option<String>,

    /// Friend's date of birth for birthday reminders
    /// Uses time::Date (not DateTime) since we only care about the date
    pub date_of_birth: Option<Date>,

    /// Freeform text of things the friend likes
    pub likes: Option<String>,

    /// Freeform text of things the friend dislikes
    pub dislikes: Option<String>,

    /// General notes about the friend
    pub notes: Option<String>,

    /// Timestamp when the friend was created
    pub created_at: OffsetDateTime,

    /// Timestamp when the friend was last updated
    pub updated_at: Option<OffsetDateTime>,
}
