//! # Friend Attribute Model
//!
//! Represents a flexible key-value attribute for a friend.
//! This allows users to store custom data beyond the core friend fields.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Database model for the `friend_attributes` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `friend_id`: Foreign key to the friend this attribute belongs to
/// - `key`: The attribute name (e.g., "favorite_color", "phone_number")
/// - `value`: The attribute value as text
/// - `value_type`: Type hint for the value (e.g., "text", "date", "number")
/// - `created_at`: When the attribute was created
/// - `updated_at`: When the attribute was last modified
///
/// # Key-Value Pattern
/// This is a flexible schema pattern (sometimes called EAV - Entity-Attribute-Value).
/// Instead of adding columns for every possible friend field, we store them as
/// key-value pairs. This allows users to define custom attributes.
///
/// # Uniqueness
/// The combination of (friend_id, key) is unique - each friend can only have
/// one value per attribute key.
///
/// # Example Attributes
/// - key: "phone_number", value: "555-1234", value_type: "text"
/// - key: "anniversary", value: "2020-06-15", value_type: "date"
/// - key: "kids_count", value: "2", value_type: "number"
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FriendAttribute {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// Foreign key to the friend this attribute belongs to
    pub friend_id: Uuid,

    /// The attribute name/key (unique per friend)
    pub key: String,

    /// The attribute value stored as text
    pub value: String,

    /// Type hint for the value - helps UI know how to display/edit
    /// Common values: "text", "date", "number", "email", "phone"
    pub value_type: String,

    /// Timestamp when the attribute was created
    pub created_at: OffsetDateTime,

    /// Timestamp when the attribute was last updated
    pub updated_at: Option<OffsetDateTime>,
}
