//! # Group Model
//!
//! Represents a user-defined group for organizing friends.
//! Groups are linked to friends via the `friend_groups` join table.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Database model for the `groups` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `user_id`: Foreign key to the owning user (for data isolation)
/// - `name`: Display name of the group (e.g., "Work", "Family", "College")
/// - `description`: Optional longer description of the group
/// - `created_at`: When the group was created
/// - `updated_at`: When the group was last modified
///
/// # Usage
/// Groups help users organize their friends into categories.
/// A friend can belong to multiple groups (many-to-many via friend_groups).
///
/// Example groups:
/// - "Work Colleagues"
/// - "Family"
/// - "Book Club"
/// - "Neighbors"
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Group {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// Foreign key to the owning user - all queries filter by this
    pub user_id: Uuid,

    /// Display name of the group
    pub name: String,

    /// Optional longer description of what this group represents
    pub description: Option<String>,

    /// Timestamp when the group was created
    pub created_at: OffsetDateTime,

    /// Timestamp when the group was last updated
    pub updated_at: Option<OffsetDateTime>,
}
