//! # User-Friend Relationship Model
//!
//! Represents how the user knows a specific friend.
//! This is different from friend-to-friend relationships - this captures
//! the user's personal connection to each friend.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Database model for the `user_friend_relationships` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `friend_id`: Foreign key to the friend
/// - `relationship_type`: How the user knows this friend
/// - `created_at`: When the relationship was created
/// - `updated_at`: When the relationship was last modified
///
/// # Purpose
/// While `friend_relationships` tracks how friends know each other,
/// this table tracks how the USER knows each friend. This is a separate
/// concept and allows for more personal categorization.
///
/// # Example relationship_types
/// - "coworker" - met at work
/// - "college_friend" - knew in college
/// - "neighbor" - lives nearby
/// - "family_friend" - connected through family
/// - "met_at_party" - met at a social event
/// - "childhood_friend" - known since childhood
///
/// # Data Isolation
/// This table doesn't need a `user_id` column because it's already
/// isolated through the `friend_id` foreign key - friends are always
/// owned by a specific user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserFriendRelationship {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// Foreign key to the friend this relationship describes
    pub friend_id: Uuid,

    /// How the user knows this friend (e.g., "coworker", "neighbor")
    pub relationship_type: String,

    /// Timestamp when the relationship was created
    pub created_at: OffsetDateTime,

    /// Timestamp when the relationship was last updated
    pub updated_at: Option<OffsetDateTime>,
}
