//! # User Model
//!
//! Represents an application user in the `users` table.
//! Users own all other data (friends, groups, etc.) which is siloed by user_id.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Database model for the `users` table.
///
/// # Fields
/// - `id`: Unique identifier (UUIDv7 generated by database)
/// - `first_name`: User's first name
/// - `last_name`: User's last name
/// - `email`: Unique email address for authentication
/// - `password_hash`: Bcrypt hashed password (never serialized to JSON)
/// - `created_at`: When the user was created (set by database)
/// - `updated_at`: When the user was last modified (managed by trigger)
///
/// # Note on password_hash
/// The `#[serde(skip_serializing)]` attribute ensures the password hash
/// is never included when this struct is serialized to JSON. This is a
/// security measure to prevent accidental password exposure in API responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// Primary key - UUID generated by the database
    pub id: Uuid,

    /// User's first name
    pub first_name: String,

    /// User's last name
    pub last_name: String,

    /// Unique email address used for login
    pub email: String,

    /// Bcrypt password hash - excluded from JSON serialization for security
    #[serde(skip_serializing)]
    pub password_hash: String,

    /// Timestamp when the user was created (database default: now())
    pub created_at: OffsetDateTime,

    /// Timestamp when the user was last updated (managed by database trigger)
    /// None if the user has never been updated after creation
    pub updated_at: Option<OffsetDateTime>,
}
